# Dockerfile

# MySql 이미지를 기반으로 이미지 생성
FROM mysql:8.0.36


ENV LC_ALL=C.UTF-8
ENV character-set-server utf8
ENV collation-server utf8_general_ci
ENV default-character-set utf8
ENV default-collation utf8_general_ci

# MySql 설정
ENV MYSQL_ROOT_PASSWORD=1111
ENV MYSQL_DATABASE=test-db
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=1111

# 포트설정
EXPOSE 3306


